[config]
default_to_workspace = false

[tasks.run-ex]
command = "cargo"
args = ["run", "--example", "playground"]

[tasks.test]
command = "cargo"
args = [
  "nextest", "run", "--workspace",
  "--status-level", "all", "--no-tests=pass",
]

[tasks.test-pkg]
command = "cargo"
args = ["nextest", "run", "--package", "${@}", "--status-level", "all", "--no-tests=pass"]
